services:
  web:
    build: .
    volumes:
      - .:/app
    image: django_blogs:v1.0
    container_name: blogs_using_django
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000 --forwarded-allow-ips='*'
    ports:
      - "8000:8000"
    env_file: 
      - .env
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: sreedhar  # Replace with your desired username
      MYSQL_PASSWORD: 996330  # Replace with your desired password
      MYSQL_ROOT_PASSWORD: 1234  # Keep this for root user access


    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_data:
