version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    image: django_blogs:v1.0
    container_name: blogs_using_django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: 
      - .env
    depends_on:
      - db
    networks:
      - django_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: blogs
      MYSQL_USER: sreedhar  
      MYSQL_PASSWORD: 996330
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3307"  
    networks:
      - django_network

volumes:
  db_data:

networks:
  django_network:
    driver: bridge
