version: 1

services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput  # Collect static files
    startCommand: gunicorn django_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      PORT: ${PORT}
      DB_NAME: ${DB_DATABASE}  # Ensure this variable is correctly named
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      EMAIL_HOST: 'smtp.gmail.com'
      EMAIL_PORT: '587'
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_USE_TLS: true  # Use boolean without quotes
