version: 1

services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn django_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      EMAIL_HOST: 'smtp.gmail.com'                  # Email host
      EMAIL_PORT: '587'                              # Email port (TLS)
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}           # Email user from environment variable
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}   # Email password from environment variable
      EMAIL_USE_TLS: 'True'                          # Use TLS
